# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.network :private_network, ip: "192.168.3.11"

  config.vm.box = "ubuntu1210"
  config.vm.box_url = "http://cloud-images.ubuntu.com/quantal/current/quantal-server-cloudimg-vagrant-i386-disk1.box"

  # Mount folder with NFS
  config.vm.synced_folder "~/Projects", "/home/vagrant/Projects", nfs: true

  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    # vb.gui = true

    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
end
